name: Test only on some files

on:
  workflow_call:
  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 2
        - name: Run build steps
          run: echo "Running the build steps"
